### ISSUE TITLE
Create mybinder notebook for future workshops

### ISSUE THREAD

**Issue by mvdbeek** [nsoranzo/bioblend-tutorial#3]
This would be even faster to get set up. This was great at the intermine workshop, we just need to add a requirements.txt file, then https://mybinder.org/v2/gh/nsoranzo/bioblend-tutorial/master should work.

**Comment by nsoranzo** [comment]
@mvdbeek Neat! It should be fine to copy/paste a user's API key in a notebook on mybinder, right?
See https://mybinder.readthedocs.io/en/latest/faq.html#how-does-mybinder-org-ensure-user-privacy and the following question.

**Comment by mvdbeek** [comment]
Yeah, I think that would be fine, we should probably still mention that it's a good idea to change the API key after the session.

**Comment by nsoranzo** [comment]
I'm going to close this, let me know if anything needs still to be done.
